app/blog/urls.py
# src/app/blog/urls.py

# Django dan third parties modules
from django.urls import path

# Locals
from app.blog import views

# app name
app_name = "blog"

urlpatterns = [
    path("posts/", views.posts_list_view, name="posts_list"),
]

app/restauran/urls.py
# src/app/restauran/urls.py

# Django dan third parties modules
from django.urls import path

# Locals
from app.restauran import views

# app name
app_name = "restauran"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("menu/", views.menu_view, name="menu"),
    path("reservasi/", views.reservasi_view, name="reservasi"),
    path("kontak/", views.kontak_view, name="kontak"),
]

app/user/urls.py
# src/app/user/urls.py

# Django dan third parties modules
from django.urls import path

# Locals
from app.user import views

# app name
app_name = "user"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
]

config/urls.py
# src/config/urls.py

# Django dan third parties modules
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # admin 
    path("admin/", admin.site.urls),

    # restauran
    path("", include("app.restauran.urls", namespace="restauran")),

    # blog
    path("", include("app.blog.urls", namespace="blog")),

    # user
    path("", include("app.user.urls", namespace="user")),
]

app/user/models.py
from django.db import models

# Create your models here.

app/blog/views.py
# src/app/blog/views.py

# Django dan third parties modules
from django.shortcuts import render

# Create your views here.


def posts_list_view(request):
	return render(request, "blog/posts-list.html")

app/restauran/views.py
# src/app/restauran/views.py

# Django dan third parties modules
from django.shortcuts import render

# Create your views here.


def home_view(request):
	return render(request, "restauran/index.html")


def about_view(request):
	return render(request, "restauran/about.html")


def menu_view(request):
	return render(request, "restauran/menu.html")


def reservasi_view(request):
	return render(request, "restauran/reservasi.html")


def kontak_view(request):
	return render(request, "restauran/kontak.html")

app/user/views.py
# src/app/user/views.py

# Django dan third parties modules
from django.shortcuts import render

# Create your views here.


def register_view(request):
	return render(request, "user/register.html")


def login_view(request):
	return render(request, "user/login.html")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Resto | Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="f62b4aa6-bdeb-41fe-83eb-9af46257578a">try{(function(w,d){!function(c,d,e,f){if(c.zaraz)console.error("zaraz is loaded twice");else{c[e]=c[e]||{};c[e].executed=[];c.zaraz={deferred:[],listeners:[]};c.zaraz._v="5714";c.zaraz.q=[];c.zaraz._f=function(g){return async function(){var h=Array.prototype.slice.call(arguments);c.zaraz.q.push({m:g,a:h})}};for(const i of["track","set","debug"])c.zaraz[i]=c.zaraz._f(i);c.zaraz.init=()=>{var j=d.getElementsByTagName(f)[0],k=d.createElement(f),l=d.getElementsByTagName("title")[0];l&&(c[e].t=d.getElementsByTagName("title")[0].text);c[e].x=Math.random();c[e].w=c.screen.width;c[e].h=c.screen.height;c[e].j=c.innerHeight;c[e].e=c.innerWidth;c[e].l=c.location.href;c[e].r=d.referrer;c[e].k=c.screen.colorDepth;c[e].n=d.characterSet;c[e].o=(new Date).getTimezoneOffset();if(c.dataLayer)for(const p of Object.entries(Object.entries(dataLayer).reduce(((q,r)=>({...q[1],...r[1]})),{})))zaraz.set(p[0],p[1],{scope:"page"});c[e].q=[];for(;c.zaraz.q.length;){const s=c.zaraz.q.shift();c[e].q.push(s)}k.defer=!0;for(const t of[localStorage,sessionStorage])Object.keys(t||{}).filter((v=>v.startsWith("_zaraz_"))).forEach((u=>{try{c[e]["z_"+u.slice(7)]=JSON.parse(t.getItem(u))}catch{c[e]["z_"+u.slice(7)]=t.getItem(u)}}));k.referrerPolicy="origin";k.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(c[e])));j.parentNode.insertBefore(k,j)};["complete","interactive"].includes(d.readyState)?zaraz.init():c.addEventListener("DOMContentLoaded",zaraz.init)}}(w,d,"zarazData","script");})(window,document)}catch(e){throw fetch("/cdn-cgi/zaraz/t"),e;};</script>
</head>
<body>
    <div class="site-wrap">

        <!-- Navbar -->
        <nav class="site-menu">
            <div class="site-menu-inner">
                <ul class="list-unstyled">
                    <li class="active"><a href="{% url 'restauran:home'%}">Home</a></li>
                    <li><a href="{% url 'restauran:about'%}">About Us</a></li>
                    <li><a href="{% url 'restauran:menu'%}">Our Menu</a></li>
                    <li><a href="{% url 'blog:posts_list'%}">Our Blog</a></li>
                    <li><a href="{% url 'restauran:reservasi'%}">Reserve A Table</a></li>
                    <li><a href="{% url 'restauran:kontak'%}">Contact</a></li>
                    <li><a href="{% url 'user:register'%}">Register</a></li>
                    <li><a href="{% url 'user:login'%}">Login</a></li>
                </ul>
            </div>
        </nav>
        <!-- Navbar ends -->

        <!-- Header  -->
        <header class="site-header">
            <div class="row align-items-center">
                <div class="col-5 col-md-3">
                    <ul class="list-unstyled social">
                        <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                        <li><a href="#"><span class="fa fa-instagram"></span></a></li>
                    </ul>
                </div>
                <div class="col-2 col-md-6 text-center">
                    <a href="{% url 'restauran:home' %}" class="site-logo">D</a>
                </div>
                <div class="col-5 col-md-3 text-right menu-burger-wrap">
                    <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>
                </div>
            </div>
        </header>
        <!-- Header ends -->

        <!-- Content -->
        {% block content %}
        {% endblock content %}
        <!-- Content ends -->

        <!-- Footer -->
        <footer>
            <div class="site-footer">
                <div class="container">
                    <div class="row small-gutters mb-5">
                        <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                            <div class="footer-widget">
                                <h3>Diner Restaurant</h3>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel neque, odio illum. Est minima sint minus sunt ducimus.</p>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                            <div class="footer-widget">
                                <h3>Lunch Service</h3>
                                <p>Booking from 12:00pm - 1:30pm</p>
                                <h3>Dinner Service</h3>
                                <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                            <div class="footer-widget">
                                <h3>Quick Links</h3>
                                <ul>
                                    <li><a href="#">Help &amp; Support</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Get in Touch</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                            <div class="footer-widget footer-contact-widget">
                                <h3>Subscribe</h3>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                <form action class="form-subscribe mb-5">
                                    <div class="form-group form-field">
                                        <input type="submit" value="Send" class="btn btn-primary">
                                        <input type="text" class="form-control" placeholder="Email">
                                    </div>
                                </form>
                                <h3>Contact Us</h3>
                                <p class="contact-email"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="f1989f979eb1889e8483959e9c90989fdf929e9c">[email&#160;protected]</a></p>
                                <p class="contact-phone">1-444-123-9829</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <div class="site-footer-copyright">
            <div class="container">
                <div class="row">
                    <p class="footer-text col-md-12">
                        Copyright &copy;<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    </p>
                </div>
            </div>
        </div>
        <!-- Footer ends -->
        
    </div>

    <!-- Loader -->
    <div id="loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" />
        </svg>
    </div>
    <!-- Loader ends -->

    <!-- Scripts -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        
        gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"89fc03ed1c7e7238","version":"2024.4.1","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
    <!-- Scripts ends -->

</body>
</html>

templates/blog/posts-list.html
<!-- src/templates/blog/posts-list.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="main-wrap">
            <div class="cover_1 cover_sm">
                <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
                    <div class="container">
                        <div class="row align-items-center justify-content-center">
                            <div class="col-md-7" data-aos="fade-up">
                                <h2 class="heading">Blog Grid</h2>
                                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="container">
                    <div class="row mb-5">
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/news_2.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/news_1.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/img_1.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/img_3.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/img_2.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                                <figure>
                                    <a href="blog-single.html"><img src="{% static 'img/img_1.jpg' %}" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="media-body">
                                    <h3><a href="blog-single.html">Food that are best for your overall health</a></h3>
                                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                                    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="pagination custom-pagination">
                                <li class="page-item prev"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a></li>
                                <li class="page-item active"><a class="page-linkx href=" #">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item next"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

templates/partials/menu-list.html
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-8" data-aos="fade-up">
                            <h2 class="mb-5 text-center">Menu List with Price</h2>
                            <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="pills-breakfast-tab" data-toggle="pill" href="#pills-breakfast" role="tab" aria-controls="pills-breakfast" aria-selected="true">Breakfast</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="pills-lunch-tab" data-toggle="pill" href="#pills-lunch" role="tab" aria-controls="pills-lunch" aria-selected="false">Brunch</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="pills-dinner-tab" data-toggle="pill" href="#pills-dinner" role="tab" aria-controls="pills-dinner" aria-selected="false">Dinner</a>
                                </li>
                            </ul>
                            <div class="tab-content" id="pills-tabContent">
                                <div class="tab-pane fade show active" id="pills-breakfast" role="tabpanel" aria-labelledby="pills-breakfast-tab">
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Warm Spinach Dip &amp; Chips</a></h3>
                                            <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$10.49</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Key Wast Machos</a></h3>
                                            <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$11.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Crispy Onions Rings</a></h3>
                                            <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$11.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Lobster &amp; Shrimp Quesadilla</a></h3>
                                            <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$13.99</strong>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="pills-lunch" role="tabpanel" aria-labelledby="pills-lunch-tab">
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Jumbo Lump Crab Stack</a></h3>
                                            <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$12.49</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Jamaican Chicken Wings</a></h3>
                                            <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$15.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Bahamian Seafood Chowder</a></h3>
                                            <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$10.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Grilled Chicken &amp; Tropical Fruit on Mixed Greens</a></h3>
                                            <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$12.99</strong>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="pills-dinner" role="tabpanel" aria-labelledby="pills-dinner-tab">
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Grilled Top Sirlion Steak</a></h3>
                                            <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$18.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Steak Oscar</a></h3>
                                            <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$23.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Skirt Steak Churrasco</a></h3>
                                            <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$20.99</strong>
                                        </div>
                                    </div>
                                    <div class="d-block d-md-flex menu-food-item">
                                        <div class="text order-1 mb-3">
                                            <h3><a href="#">Grilled Beef Steak</a></h3>
                                            <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                                        </div>
                                        <div class="price order-2">
                                            <strong>$20.99</strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>